spring:
  application:
    name: "apmax-server"

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:file:~/.apmax/env"
    username: "sa"
    password: ""

---
server:
  port: 8888
